apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: impersonation-sync
  namespace: argocd
spec:
  destinations:
  - namespace: guestbook-dev
    server: https://kubernetes.default.svc
  destinationServiceAccounts:
  - defaultServiceAccount: guestbook-dev-sa
    namespace: guestbook-dev
    server: https://kubernetes.default.svc
  sourceRepos:
  - 'https://github.com/reggie-k/argocd-tests.git'          
