apiVersion: batch/v1
kind: Job
metadata:
  generateName: terminate-on-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: busybox
          command: ["echo", "hello"]
      restartPolicy: Never