base:
  version: 1.27.5
  rollout: true
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 8m
        - setWeight: 100
        - pause:
            duration: 2m
