apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dual-generator
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          files:
          - path: apps/**/stage/Chart.yaml
          repoURL: https://github.com/kostis-codefresh/many-charts.git
          revision: HEAD
      - git:
          files:
          - path: apps/{{ index .path.segments 1 }}/stage/values.yaml
          repoURL: https://github.com/kostis-codefresh/many-charts.git
          revision: HEAD
  goTemplate: true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.helm.parameters[] | select(.name == "global.image.tag" or .name
      == "global.image.repository")
  syncPolicy:
    preserveResourcesOnDeletion: true      
  template:
    metadata:
      labels:
        app: '{{ index .path.segments 1 }}'
        environment: '{{ index .path.segments 2 }}'
      name: '{{ index .path.segments 1 }}-{{ index .path.segments 2 }}'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        helm:
          parameters:
          - name: argocdAppName
            value: $ARGOCD_APP_NAME
          - name: global.environment
            value: stage
          - name: global.cluster.name
            value: apps
          - name: global.cluster.region
            value: us-east-1
        path: '{{ .path.path }}'
        repoURL: https://github.com/kostis-codefresh/many-charts.git

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 1 }}'

      ignoreDifferences:
      - group: apps
        jqPathExpressions:
        - .spec.template.metadata.annotations?["kubectl.kubernetes.io/restartedAt"]
          // empty
        kind: '*'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - ApplyOutOfSyncOnly=false
          - PreserveResourcesOnDeletion=true
          - RespectIgnoreDifferences=true          
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).