apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded, BeforeHookCreation
    "argocd.argoproj.io/sync-wave": "-1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: default
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded, BeforeHookCreation
    "argocd.argoproj.io/sync-wave": "2"
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: my-container
          image: busybox
          command: ["echo", "hello"]