apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocon-demo
  namespace: argocd
spec:
  destination:
    namespace: argocon-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
