apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: kuku
  destination:
    namespace: kuku
    server: 'https://kubernetes.default.svc'
  source:
    path: api
    repoURL: 'https://github.com/reggie-k/argocd-tests.git'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
