apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-nginx'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: manifests/nginx
        repoURL: 'https://github.com/reggie-k/argocd-tests.git'
        targetRevision: main
      destination:
        server: '{{server}}'
        namespace: nginx