apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-generator
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      # github:
      #   # The GitHub organization or user.
      #   owner: reggie-k
      #   # The Github repository
      #   repo: argocd-tests11111
 
      #   # tokenRef:
      #   #   secretName: github-token
      #   #   key: token
      #   # appSecretName: repo-4246007479
      #   # Labels is used to filter the PRs that you want to target. (optional)
      #   labels:
      #   - preview
      # requeueAfterSeconds: 5

      gitlab:
   
        project: regina.voloshin-project123

  template:
    metadata:
      annotations:
        # argocd.argoproj.io/manifest-generate-paths: apps/{{ .values.appName }}/stage/preview
      
        pr_head_sha: '{{ .head_sha }}'
        pr_number: '{{ .number }}'
      labels:
        app: 'simple-uc-pr'
        environment: stage
      name: 'simple-uc-pr'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: 'simple-uc-pr-{{ .number }}'
      project: 'default'
      source:
        path: manifests/simple-uc
        repoURL: https://github.com/reggie-k/argocd-tests.git
        targetRevision: '{{.branch}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PrunePropagationPolicy=foreground
        - Replace=false
        - PruneLast=false
        - Validate=true
        - ApplyOutOfSyncOnly=false
        - PreserveResourcesOnDeletion=false
        - CreateNamespace=true  