apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: scm-generator
spec:
  generators:
  - scmProvider:
      github:
        # The GitHub organization to scan.
        organization: reggie-k
        # For GitHub Enterprise:
        # api: https://git.example.com/
        # If true, scan every branch of every repository. If false, scan only the default branch. Defaults to false.
        # allBranches: true
        # Reference to a Secret containing an access token. (optional)
        # tokenRef:
        #   secretName: github-token
        #   key: token
        # (optional) use a GitHub App to access the API instead of a PAT.
        # appSecretName: gh-app-repo-creds
      requeueAfterSeconds: 20
  template:
    metadata:
      annotations:
        # argocd.argoproj.io/manifest-generate-paths: apps/{{ .values.appName }}/stage/preview
        github_repo: '{{ .repository }}'
        pr_head_sha: '{{ .head_sha }}'
        pr_number: '{{ .number }}'
      labels:
        app: '{{ .values.appName }}'
        environment: stage
      name: '{{ .values.appName }}--pr-{{ .number }}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .values.appName }}--pr-{{ .number }}'
      project: 'default'
      source:
        path: manifests/simple-uc
        repoURL: https://github.com/reggie-k/argocd-tests.git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PrunePropagationPolicy=foreground
        - Replace=false
        - PruneLast=false
        - Validate=true
        - ApplyOutOfSyncOnly=false
        - PreserveResourcesOnDeletion=false
        - CreateNamespace=true  
