base:
  version: 1.23.4
  rollout: true
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 8m
        - setWeight: 100
        - pause:
            duration: 2m
