apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
spec:
  project: impersonation-sync
  destination:
    namespace: guestbook-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/impersonation-sync/guestbook-dev
    repoURL: 'https://github.com/reggie-k/argocd-tests.git'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true    
