apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: post-sync-hooks-order
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/reggie-k/argocd-tests.git'
    targetRevision: main
    path: manifests/post-sync-hooks-order
  destination:
    server: https://kubernetes.default.svc
    namespace: kuku
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true 