apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-health
spec:
  project: default
  destination:
    namespace: kuku
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/rollout-health
    repoURL: 'https://github.com/reggie-k/argocd-tests.git'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true   
