apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-source-app-no-resync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michalpl-monday/argocd-sync-bug-repro-1
    targetRevision: main
    path: test-app/my-app
    helm:
      parameters:
        - name: image.repository
          value: nginx
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true 