apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: none-impersonation-sync
  namespace: argocd
spec:
  destinations:
  - namespace: guestbook-staging
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  sourceRepos:
  - 'https://github.com/reggie-k/argocd-tests.git'          
