apiVersion: batch/v1
kind: Job
metadata:
  name: hello-27863954
  namespace: kuku
spec:
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: hello-27863954
    spec:
      containers:
        - command:
            - /bin/sh
            - '-c'
            - date; echo Hello from the Kubernetes cluster
          image: 'busybox:1.28'
          imagePullPolicy: IfNotPresent
          name: hello
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: OnFailure
